spring:
  profiles:
    active: @profileActive@
  config:
    import: "optional:nacos:idea-island-${spring.profiles.active}.yaml"
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yaml
        refresh-enabled: true
